# Generated by Django 6.0.1 on 2026-03-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArPvpRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('game_slug', models.CharField(default='ar_bets', max_length=64)),
                ('max_players', models.PositiveSmallIntegerField(default=2)),
                ('host_session_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('in_round', 'In round'), ('round_result', 'Round result'), ('finished', 'Finished')], default='lobby', max_length=20)),
                ('target_score', models.PositiveSmallIntegerField(default=5)),
                ('round_number', models.PositiveIntegerField(default=0)),
                ('round_payload', models.JSONField(blank=True, default=dict)),
                ('round_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArPvpPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128)),
                ('display_name', models.CharField(default='Игрок', max_length=64)),
                ('seat_no', models.PositiveSmallIntegerField(default=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('answered_round', models.PositiveIntegerField(default=0)),
                ('last_answer_correct', models.BooleanField(default=False)),
                ('last_answer_ms', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ar.arpvproom')),
            ],
            options={
                'ordering': ('seat_no', 'joined_at'),
                'unique_together': {('room', 'session_key')},
            },
        ),
    ]
