# Generated by Django 6.0.1 on 2026-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arpvproom',
            name='max_chips',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='arpvproom',
            name='min_chips',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arpvproom',
            name='stacks_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='arpvproom',
            name='timer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arpvproom',
            name='timer_seconds',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='arpvproom',
            name='use_stacks',
            field=models.BooleanField(default=True),
        ),
    ]
