# Generated by Django 6.0.1 on 2026-03-30 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0002_arpvproom_max_chips_arpvproom_min_chips_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArTrainingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_slug', models.CharField(db_index=True, max_length=64)),
                ('outcome', models.CharField(choices=[('correct', 'Correct'), ('almost', 'Almost'), ('wrong', 'Wrong'), ('skipped', 'Skipped')], db_index=True, max_length=16)),
                ('solve_seconds', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_training_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
