# Generated by Django 6.0.1 on 2026-04-02 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время')),
                ('path', models.CharField(db_index=True, max_length=512, verbose_name='путь')),
                ('query_string', models.CharField(blank=True, max_length=512, verbose_name='query')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='код ответа')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='сессия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_page_visits', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'просмотр страницы',
                'verbose_name_plural': 'просмотры страниц',
                'ordering': ['-created_at'],
            },
        ),
    ]
