# Generated by Django 5.2.3 on 2026-04-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_create_boomerang_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SopGameTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='код URL')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
            ],
            options={
                'verbose_name': 'тест СОП',
                'verbose_name_plural': 'тесты СОП',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SopQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='вопрос')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='homepage.sopgametest', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'вопрос СОП',
                'verbose_name_plural': 'вопросы СОП',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SopAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='верный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='homepage.sopquestion', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'вариант ответа',
                'verbose_name_plural': 'варианты ответа',
                'ordering': ['id'],
            },
        ),
    ]
