# Generated by Django 5.2.3 on 2026-04-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_sop_quiz_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepagevisit',
            name='content_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Content-Type'),
        ),
        migrations.AddField(
            model_name='sitepagevisit',
            name='http_method',
            field=models.CharField(db_index=True, default='GET', max_length=10, verbose_name='метод'),
        ),
        migrations.AlterField(
            model_name='sitepagevisit',
            name='status_code',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='код ответа'),
        ),
    ]
