# Generated by Django 5.2.3 on 2026-04-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_site_visit_full_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepagevisit',
            options={'ordering': ['-created_at'], 'verbose_name': 'запрос к сайту', 'verbose_name_plural': 'запросы к сайту'},
        ),
    ]
